version: "3"
services:
    nginx:
      image: nginx:1.19
      volumes:
        - ./nginx.conf:/tmp/nginx.conf
        - ./output/nginx/log:/var/log/nginx
      ports:
        - "80:80"
      env_file:
        - nginx.env
      command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    table-view:
      image: inraep2m2/table-view-discovery:0.0.2
      volumes:
        - ./endpoints.js:/usr/local/apache2/htdocs/endpoints.js     
