version: "3"
services:
  ##  - NGINX -
  ##  routage des services
  ##  - VIRTUOSO => MetaboRef
  ##  - Table-View-Discovery
  ##
    nginx:
      image: nginx:1.19
      volumes:
        - ./nginx.conf:/tmp/nginx.conf
        - ./nginx_log:/var/log/nginx
      ports:
        - ${EXPOSE_PORT}:80
      env_file:
        - nginx.env
      command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

   ## IHM 1 - Table-View-Discovery
    table-view:
      image: inraep2m2/discovery-table-view:latest
      volumes:
        - ./endpoints.js:/usr/local/apache2/htdocs/endpoints.js

   ## Rdf Database - Virtuoso -  MetaboRef
    metaboref_virtuoso:
      image: tenforce/virtuoso:virtuoso7.2.5
      container_name: metaboref_virtuoso
      environment:
          VIRT_Parameters_NumberOfBuffers: 340000   # See virtuoso/README.md to adapt value of this line
          VIRT_Parameters_MaxDirtyBuffers: 250000    # See virtuoso/README.md to adapt value of this line
          VIRT_Parameters_TN_MAX_memory: 4000000000
          VIRT_SPARQL_ResultSetMaxRows: 100000000
          VIRT_SPARQL_MaxDataSourceSize: 1000000000
          VIRT_Flags_TN_MAX_memory: 4000000000
          VIRT_Parameters_StopCompilerWhenXOverRunTime: 1
          VIRT_SPARQL_MaxQueryCostEstimationTime: 0       # query time estimation
          VIRT_SPARQL_MaxQueryExecutionTime: 300          # 5 min
          VIRT_Parameters_MaxMemPoolSize: 800000000
          VIRT_Database_LockFile: virtuoso.lck
          LOGIN_PASSWORD: ${LOGIN_VIRTUOSO}
          DBA_PASSWORD: ${PASSWORD_VIRTUOSO}
          SPARQL_UPDATE: "true"
          DEFAULT_GRAPH: "http://p2m2.metabohub.org/graph"
      volumes:
          - ./virtuoso_data:/data
          - ./metaboref_data:/usr/local/virtuoso-opensource/share/virtuoso/vad/dumps
      ports:
          - 8890:8890

      command: >
        bash -c '
        bash /virtuoso.sh & sleep 6 &&
        until [ -f "/usr/local/virtuoso-opensource/share/virtuoso/vad/dumps/load_metaboref.sh" ] ; do
              echo "Waiting Metaboref turtle file - sleeping"
              sleep 5
        done &&
        bash /usr/local/virtuoso-opensource/share/virtuoso/vad/dumps/load_metaboref.sh &&
        wait'

  ## -------------------------------------------------
  ## Construction de MetaboRef
  ##
    metaboref:
      image: inraep2m2/database-metaboref:latest
      container_name: metaboref
      depends_on : [metaboref_virtuoso]
      volumes:
          - ./metaboref_data:/ttl
  ## -------------------------------------------------
  ## Activation de CORS dans VIRTUOSO
  ##
    selenium_cors:
      image: inraep2m2/service-allow-cors-virtuoso:latest
      environment:
          virtuoso_site: "http://metaboref_virtuoso:8890/"
          login: ${LOGIN_VIRTUOSO}
          passwd: ${PASSWORD_VIRTUOSO}
          chrome_container: chrome
      depends_on: [ chrome, metaboref_virtuoso ]

      command: >
          bash -c 'sleep 3m && echo " **** configure CORS / Virtuoso  ****" && node virtuoso_cors.js'

  ## -------------------------------------------------
  ## Chrome Pour Selenium
  ##
    chrome:
      container_name: chrome
      image: selenium/standalone-chrome
      environment:
          START_XVFB: 'false'
